import pytest

from db.repositories.collect_repository import CollectRepository

pytestmark = pytest.mark.integration


class TestFindServerId:
    async def test_not_found_returns_none(self, db_session): ...
    async def test_found_returns_int(self, db_session): ...


class TestUpsertServer:
    async def test_insert_returns_server_id(self, db_session): ...
    async def test_same_machine_id_updates_fields(self, db_session): ...
    async def test_upsert_returns_same_id_on_conflict(self, db_session): ...


class TestInsertMetric:
    async def test_inserts_server_metrics_row(self, db_session): ...
    async def test_inserts_disk_io_rows(self, db_session): ...
    async def test_inserts_net_io_rows(self, db_session): ...
    async def test_inserts_mount_usage_rows(self, db_session): ...
    async def test_empty_disk_io_skips_insert(self, db_session): ...
    async def test_empty_net_io_skips_insert(self, db_session): ...