import pytest

from db.repositories.query_repository import QueryRepository

pytestmark = pytest.mark.integration


class TestListServers:
    async def test_empty_db_returns_empty_list(self, db_session): ...
    async def test_returns_all_servers(self, db_session): ...
    async def test_search_filters_by_hostname(self, db_session): ...
    async def test_pagination_offsets_correctly(self, db_session): ...
    async def test_last_seen_at_from_metrics_when_available(self, db_session): ...
    async def test_last_seen_at_from_inventory_when_no_metrics(self, db_session): ...


class TestGetServer:
    async def test_not_found_returns_none(self, db_session): ...
    async def test_found_returns_full_dto(self, db_session): ...


class TestGetStorage:
    async def test_not_found_returns_none(self, db_session): ...
    async def test_found_with_mount_usage(self, db_session): ...
    async def test_found_without_mount_usage(self, db_session): ...


class TestGetNetwork:
    async def test_not_found_returns_none(self, db_session): ...
    async def test_found_with_net_io(self, db_session): ...


class TestGetCollectionStatus:
    async def test_returns_none_timestamps_when_no_data(self, db_session): ...
    async def test_last_metric_at_populated_when_metrics_exist(self, db_session): ...


class TestLatestDashboard:
    async def test_no_server_returns_none(self, db_session): ...
    async def test_no_metrics_returns_empty_metrics_list(self, db_session): ...
    async def test_two_readings_returned_for_delta(self, db_session): ...
    async def test_disk_io_grouped_by_device(self, db_session): ...
    async def test_net_io_grouped_by_interface(self, db_session): ...


class TestMetricSnapshots:
    async def test_no_data_returns_empty(self, db_session): ...
    async def test_ordered_desc_by_collected_at(self, db_session): ...
    async def test_cursor_excludes_items_at_or_after(self, db_session): ...


class TestMetricChart:
    async def test_no_data_returns_empty(self, db_session): ...
    async def test_cpu_chart_returns_time_bucketed_data(self, db_session): ...
    async def test_disk_chart_filtered_by_dimension(self, db_session): ...
    async def test_net_chart_filtered_by_dimension(self, db_session): ...
    async def test_fs_chart_filtered_by_dimension(self, db_session): ...