import pytest

from consumer.schemas import AgentMessage, ErrorInput, InventoryInput, MetricsInput

pytestmark = pytest.mark.unit


class TestCommonMeta:
    def test_empty_agent_version_rejected(self): ...
    def test_empty_hostname_rejected(self): ...
    def test_invalid_message_id_rejected(self): ...
    def test_invalid_collected_at_rejected(self): ...


class TestInventoryInput:
    def test_minimal_required_fields_parsed(self): ...
    def test_empty_machine_id_rejected(self): ...
    def test_cpu_cores_zero_rejected(self): ...
    def test_mem_total_kb_zero_rejected(self): ...
    def test_optional_fields_accept_none(self): ...
    def test_ip_external_none_vs_empty_list(self): ...
    def test_disks_defaults_to_empty(self): ...
    def test_mounts_defaults_to_empty(self): ...


class TestMetricsInput:
    def test_minimal_fields_parsed(self): ...
    def test_all_cpu_fields_optional(self): ...
    def test_all_mem_fields_optional(self): ...
    def test_disk_io_defaults_to_empty(self): ...
    def test_net_io_defaults_to_empty(self): ...
    def test_mounts_defaults_to_empty(self): ...


class TestErrorInput:
    def test_minimal_fields_parsed(self): ...
    def test_invalid_failed_component_rejected(self): ...
    def test_empty_error_code_rejected(self): ...
    def test_empty_error_message_rejected(self): ...


class TestAgentMessageUnion:
    def test_inventory_discriminated_correctly(self): ...
    def test_metrics_discriminated_correctly(self): ...
    def test_error_discriminated_correctly(self): ...
    def test_unknown_message_type_rejected(self): ...
    def test_json_round_trip(self): ...