import pytest

from web.services.query_service import QueryService

pytestmark = pytest.mark.unit


class TestListServers:
    async def test_empty_repo_returns_empty_list(self): ...
    async def test_passes_page_limit_search_to_repo(self): ...
    async def test_online_status_resolved_from_redis(self): ...
    async def test_is_online_filter_applied_in_service(self): ...


class TestGetServer:
    async def test_not_found_returns_none(self): ...
    async def test_found_returns_server_detail_response(self): ...
    async def test_cache_hit_skips_repo(self): ...
    async def test_cache_miss_populates_cache(self): ...


class TestGetStorage:
    async def test_not_found_returns_none(self): ...
    async def test_found_returns_storage_detail(self): ...


class TestGetNetwork:
    async def test_not_found_returns_none(self): ...
    async def test_found_returns_network_detail(self): ...


class TestGetCollectionStatus:
    async def test_passes_server_id_to_repo(self): ...
    async def test_online_flag_from_redis(self): ...


class TestGetLatestMetric:
    async def test_not_found_returns_none(self): ...
    async def test_found_returns_dashboard(self): ...
    async def test_cache_hit_skips_repo(self): ...
    async def test_cache_miss_populates_cache(self): ...


class TestGetMetricSnapshots:
    async def test_empty_returns_empty_list(self): ...
    async def test_passes_cursor_and_limit(self): ...


class TestGetMetricChart:
    async def test_invalid_metric_type_returns_empty_without_repo_call(self): ...
    async def test_valid_params_delegated_to_repo(self): ...