import pytest

from web.services.mappers import (
    to_collection_status_item,
    to_metric_series_item,
    to_network_detail,
    to_server_detail,
    to_server_list_item,
    to_storage_detail,
)

pytestmark = pytest.mark.unit


class TestToServerListItem:
    def test_fields_mapped_correctly(self): ...
    def test_mem_converted_kb_to_gb(self): ...
    def test_is_online_defaults_false(self): ...


class TestToServerDetail:
    def test_all_fields_mapped(self): ...
    def test_disk_size_converted_bytes_to_gb(self): ...
    def test_mem_and_swap_converted_to_gb(self): ...


class TestToStorageDetail:
    def test_inventory_mounts_merged_with_live_usage(self): ...
    def test_live_only_mount_appended(self): ...
    def test_mounts_sorted_by_path(self): ...
    def test_no_usage_data_yields_none_pct(self): ...


class TestToNetworkDetail:
    def test_fields_mapped_correctly(self): ...
    def test_net_io_delta_delegated_to_compute_net_io(self): ...


class TestToCollectionStatusItem:
    def test_is_online_flag_set(self): ...
    def test_timestamps_passed_through(self): ...


class TestToMetricSeriesItem:
    def test_fields_mapped_correctly(self): ...