import pytest

from web.services.metrics_calculator import (
    build_dashboard,
    compute_cpu,
    compute_disk_io,
    compute_mem,
    compute_mounts,
    compute_net_io,
    compute_swap,
)

pytestmark = pytest.mark.unit


class TestComputeCpu:
    def test_no_readings_returns_none(self): ...
    def test_single_reading_returns_none_pcts(self): ...
    def test_two_readings_calculates_usage_pct(self): ...
    def test_zero_delta_total_returns_none(self): ...
    def test_counter_reset_negative_delta_returns_none(self): ...


class TestComputeMem:
    def test_no_reading_returns_none(self): ...
    def test_used_calculated_from_total_minus_available(self): ...
    def test_usage_pct_calculated(self): ...
    def test_none_available_yields_none_used(self): ...


class TestComputeSwap:
    def test_zero_swap_total_returns_none(self): ...
    def test_used_calculated_correctly(self): ...


class TestComputeDiskIo:
    def test_single_sample_returns_none_rates(self): ...
    def test_two_samples_calculates_iops_and_kbps(self): ...
    def test_counter_reset_returns_none(self): ...
    def test_zero_interval_returns_none(self): ...
    def test_multiple_devices_returned_sorted(self): ...


class TestComputeNetIo:
    def test_single_sample_returns_none_rates(self): ...
    def test_two_samples_calculates_kbps_and_pps(self): ...
    def test_counter_reset_returns_none(self): ...
    def test_multiple_interfaces_returned_sorted(self): ...


class TestComputeMounts:
    def test_usage_pct_calculated(self): ...
    def test_sorted_by_mount_path(self): ...
    def test_zero_total_bytes_yields_none_pct(self): ...


class TestBuildDashboard:
    def test_empty_metrics_list_handled(self): ...
    def test_single_reading_yields_none_cpu_pcts(self): ...
    def test_two_readings_populates_all_fields(self): ...