"""initial schema

Revision ID: b8f8ffd882f7
Revises: 
Create Date: 2026-05-10 04:26:21.778392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8f8ffd882f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # TimescaleDB extension — 시계열 5개 테이블의 hypertable 변환에 필수.
    # CASCADE — 의존 객체 (예: timescaledb_information.* 뷰) 동시 생성.
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('os_id', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('os_codename', sa.String(length=64), nullable=True),
    sa.Column('kernel_version', sa.String(length=64), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('mem_total_kb', sa.BigInteger(), nullable=True),
    sa.Column('swap_total_kb', sa.BigInteger(), nullable=True),
    sa.Column('boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_internal', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ip_external', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('disks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('listen_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('server_disk_io',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.Column('reads_completed', sa.BigInteger(), nullable=True),
    sa.Column('writes_completed', sa.BigInteger(), nullable=True),
    sa.Column('sectors_read', sa.BigInteger(), nullable=True),
    sa.Column('sectors_written', sa.BigInteger(), nullable=True),
    sa.Column('boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_inventory.id'], ),
    sa.PrimaryKeyConstraint('id', 'collected_at'),
    sa.UniqueConstraint('server_id', 'device', 'collected_at', name='uq_server_disk_io_sid_dev_ts')
    )
    op.create_table('server_inventory_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('os_id', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('os_codename', sa.String(length=64), nullable=True),
    sa.Column('kernel_version', sa.String(length=64), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('mem_total_kb', sa.BigInteger(), nullable=True),
    sa.Column('swap_total_kb', sa.BigInteger(), nullable=True),
    sa.Column('boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_internal', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ip_external', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('disks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('listen_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_inventory.id'], ),
    sa.PrimaryKeyConstraint('id', 'collected_at'),
    sa.UniqueConstraint('server_id', 'collected_at', name='uq_server_inv_history_sid_ts')
    )
    op.create_table('server_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('cpu_user', sa.BigInteger(), nullable=True),
    sa.Column('cpu_nice', sa.BigInteger(), nullable=True),
    sa.Column('cpu_system', sa.BigInteger(), nullable=True),
    sa.Column('cpu_idle', sa.BigInteger(), nullable=True),
    sa.Column('cpu_iowait', sa.BigInteger(), nullable=True),
    sa.Column('cpu_irq', sa.BigInteger(), nullable=True),
    sa.Column('cpu_softirq', sa.BigInteger(), nullable=True),
    sa.Column('cpu_steal', sa.BigInteger(), nullable=True),
    sa.Column('mem_total_kb', sa.BigInteger(), nullable=True),
    sa.Column('mem_free_kb', sa.BigInteger(), nullable=True),
    sa.Column('mem_available_kb', sa.BigInteger(), nullable=True),
    sa.Column('mem_buffers_kb', sa.BigInteger(), nullable=True),
    sa.Column('mem_cached_kb', sa.BigInteger(), nullable=True),
    sa.Column('swap_total_kb', sa.BigInteger(), nullable=True),
    sa.Column('swap_free_kb', sa.BigInteger(), nullable=True),
    sa.Column('load_1m', sa.Float(), nullable=True),
    sa.Column('load_5m', sa.Float(), nullable=True),
    sa.Column('load_15m', sa.Float(), nullable=True),
    sa.Column('boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_inventory.id'], ),
    sa.PrimaryKeyConstraint('id', 'collected_at'),
    sa.UniqueConstraint('server_id', 'collected_at', name='uq_server_metrics_sid_ts')
    )
    op.create_table('server_mount_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('mount', sa.String(length=255), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('free_bytes', sa.BigInteger(), nullable=True),
    sa.Column('avail_bytes', sa.BigInteger(), nullable=True),
    sa.Column('boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_inventory.id'], ),
    sa.PrimaryKeyConstraint('id', 'collected_at'),
    sa.UniqueConstraint('server_id', 'mount', 'collected_at', name='uq_server_mount_usage_sid_mnt_ts')
    )
    op.create_table('server_net_io',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(length=64), nullable=False),
    sa.Column('rx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('tx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('rx_packets', sa.BigInteger(), nullable=True),
    sa.Column('tx_packets', sa.BigInteger(), nullable=True),
    sa.Column('rx_errors', sa.Integer(), nullable=True),
    sa.Column('tx_errors', sa.Integer(), nullable=True),
    sa.Column('boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_inventory.id'], ),
    sa.PrimaryKeyConstraint('id', 'collected_at'),
    sa.UniqueConstraint('server_id', 'interface', 'collected_at', name='uq_server_net_io_sid_iface_ts')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_server_id', sa.Integer(), nullable=False),
    sa.Column('target_machine_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['target_server_id'], ['server_inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_tasks_target_machine_id'), 'tasks', ['target_machine_id'], unique=False)
    op.create_index('uq_tasks_pending_per_server_type', 'tasks', ['target_server_id', 'task_type'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###

    # 시계열 5개 테이블 → TimescaleDB hypertable 변환. autogenerate 미지원이라 수동 보강.
    # if_not_exists=true — 멱등성 (downgrade·재시도 안전).
    for table in ("server_metrics", "server_disk_io", "server_net_io",
                  "server_mount_usage", "server_inventory_history"):
        op.execute(
            f"SELECT create_hypertable('{table}', 'collected_at', if_not_exists => true)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tasks_pending_per_server_type', table_name='tasks', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_tasks_target_machine_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('server_net_io')
    op.drop_table('server_mount_usage')
    op.drop_table('server_metrics')
    op.drop_table('server_inventory_history')
    op.drop_table('server_disk_io')
    op.drop_table('server_inventory')
    # ### end Alembic commands ###
