import pytest

pytestmark = pytest.mark.unit


class TestCollectionStatusApi:
    async def test_returns_200_with_list(self): ...
    async def test_server_id_passed_to_service(self): ...


class TestLatestMetricApi:
    async def test_not_found_returns_404(self): ...
    async def test_found_returns_200_json(self): ...
    async def test_server_id_passed_to_service(self): ...


class TestMetricSnapshotsApi:
    async def test_returns_200_list(self): ...
    async def test_default_params_used(self): ...
    async def test_cursor_param_forwarded(self): ...
    async def test_limit_param_forwarded(self): ...


class TestMetricChartApi:
    async def test_missing_metric_type_returns_422(self): ...
    async def test_invalid_metric_type_returns_422(self): ...
    async def test_returns_200_list(self): ...
    async def test_default_time_params_used(self): ...
    async def test_all_params_forwarded_to_service(self): ...