import pytest

pytestmark = pytest.mark.unit


class TestHealth:
    async def test_returns_ok(self): ...


class TestListServersPage:
    async def test_returns_200_html(self): ...
    async def test_default_params_passed_to_service(self): ...
    async def test_search_and_filter_params_forwarded(self): ...


class TestGetServerPage:
    async def test_not_found_returns_404(self): ...
    async def test_found_returns_200_html(self): ...
    async def test_server_id_passed_to_service(self): ...


class TestGetStoragePage:
    async def test_not_found_returns_404(self): ...
    async def test_found_returns_200_html(self): ...


class TestGetNetworkPage:
    async def test_not_found_returns_404(self): ...
    async def test_found_returns_200_html(self): ...


class TestGetChartPage:
    async def test_not_found_returns_404(self): ...
    async def test_found_returns_200_html(self): ...