"""v2 wire schema baseline

wire v2 (OpenTelemetry system.* 정렬) 데이터 계약의 스토리지 스키마 단일 baseline.
단위 canonical — 시간 s(Float), 크기 By(BigInteger). device/iface 축 = 안정 id 문자열.
시계열 = host 집계(server_metrics) + 자식 6종(disk_io·net_io·filesystem·cpu_core·pressure·disk_error).
envelope 메타(boot_time/agent_started_at)는 server_metrics 에만 — 자식은 (server_id, collected_at) 로 참조.
counter reset 은 집계 계층 counter_agg 가 흡수하므로 자식 시계열에 reset gate 컬럼 없음.

Revision ID: 53df4c2132fd
Revises:
Create Date: 2026-07-09 11:51:36.804568

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "53df4c2132fd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# collected_at 으로 hypertable 변환할 시계열 테이블 (host 집계 + 자식 6종 + inventory 이력).
_HYPERTABLES = (
    "server_metrics",
    "server_disk_io",
    "server_net_io",
    "server_filesystem",
    "server_cpu_core",
    "server_pressure",
    "server_disk_error",
    "server_inventory_history",
)


def upgrade() -> None:
    """Upgrade schema."""
    # TimescaleDB extension — 시계열 hypertable 변환에 필수. CASCADE 로 의존 객체 동시 생성.
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnostic_jobs",
        sa.Column("id", sa.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_type", sa.String(length=32), server_default="customer_report", nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("input_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress_stage", sa.String(length=32), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_by", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_diagnostic_jobs_active_per_input",
        "diagnostic_jobs",
        ["scope", "input_hash", "job_type"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.create_table(
        "server_inventory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("agent_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("composite_id", sa.String(length=64), nullable=True),
        sa.Column("machine_id", sa.String(length=64), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("os_family", sa.String(length=16), nullable=True),
        sa.Column("os_id", sa.String(length=64), nullable=True),
        sa.Column("os_version", sa.String(length=64), nullable=True),
        sa.Column("os_codename", sa.String(length=64), nullable=True),
        sa.Column("kernel_version", sa.String(length=64), nullable=True),
        sa.Column("cpu_cores", sa.Integer(), nullable=True),
        sa.Column("cpu_model", sa.String(length=255), nullable=True),
        sa.Column("mem_total_bytes", sa.BigInteger(), nullable=True),
        sa.Column("boot_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("block_devices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("net_interfaces", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("lvm_vgs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_external", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("services", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("listen_ports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("service_categories", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", name="uq_server_inventory_agent_id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "ix_server_inventory_service_categories",
        "server_inventory",
        ["service_categories"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "server_cpu_core",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("core_id", sa.Integer(), nullable=False),
        sa.Column("cpu_user_s", sa.Float(), nullable=True),
        sa.Column("cpu_nice_s", sa.Float(), nullable=True),
        sa.Column("cpu_system_s", sa.Float(), nullable=True),
        sa.Column("cpu_idle_s", sa.Float(), nullable=True),
        sa.Column("cpu_iowait_s", sa.Float(), nullable=True),
        sa.Column("cpu_irq_s", sa.Float(), nullable=True),
        sa.Column("cpu_softirq_s", sa.Float(), nullable=True),
        sa.Column("cpu_steal_s", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
        sa.UniqueConstraint("server_id", "core_id", "collected_at", name="uq_server_cpu_core_sid_core_ts"),
    )
    op.create_table(
        "server_disk_error",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("error_kind", sa.String(length=32), nullable=False),
        sa.Column("error_class", sa.String(length=64), nullable=False),
        sa.Column("member", sa.String(length=128), server_default=sa.text("''"), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
        sa.UniqueConstraint(
            "server_id",
            "device_id",
            "error_kind",
            "error_class",
            "member",
            "collected_at",
            name="uq_server_disk_error_nk",
        ),
    )
    op.create_table(
        "server_disk_io",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("device_name", sa.String(length=128), nullable=True),
        sa.Column("io_read_bytes", sa.BigInteger(), nullable=True),
        sa.Column("io_write_bytes", sa.BigInteger(), nullable=True),
        sa.Column("ops_read", sa.BigInteger(), nullable=True),
        sa.Column("ops_write", sa.BigInteger(), nullable=True),
        sa.Column("io_time_s", sa.Float(), nullable=True),
        sa.Column("op_read_time_s", sa.Float(), nullable=True),
        sa.Column("op_write_time_s", sa.Float(), nullable=True),
        sa.Column("pending_ops", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
        sa.UniqueConstraint("server_id", "device_id", "collected_at", name="uq_server_disk_io_sid_dev_ts"),
    )
    op.create_table(
        "server_filesystem",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("mountpoint", sa.String(length=255), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=True),
        sa.Column("fstype", sa.String(length=32), nullable=True),
        sa.Column("used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("free_bytes", sa.BigInteger(), nullable=True),
        sa.Column("inodes_used", sa.BigInteger(), nullable=True),
        sa.Column("inodes_free", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
        sa.UniqueConstraint("server_id", "mountpoint", "collected_at", name="uq_server_filesystem_sid_mnt_ts"),
    )
    op.create_table(
        "server_inventory_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("os_family", sa.String(length=16), nullable=True),
        sa.Column("os_id", sa.String(length=64), nullable=True),
        sa.Column("os_version", sa.String(length=64), nullable=True),
        sa.Column("os_codename", sa.String(length=64), nullable=True),
        sa.Column("kernel_version", sa.String(length=64), nullable=True),
        sa.Column("cpu_cores", sa.Integer(), nullable=True),
        sa.Column("cpu_model", sa.String(length=255), nullable=True),
        sa.Column("mem_total_bytes", sa.BigInteger(), nullable=True),
        sa.Column("boot_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("block_devices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("net_interfaces", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("lvm_vgs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_external", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("services", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("listen_ports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
        sa.UniqueConstraint("server_id", "collected_at", name="uq_server_inv_history_sid_ts"),
    )
    op.create_table(
        "server_metrics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("cpu_user_s", sa.Float(), nullable=True),
        sa.Column("cpu_nice_s", sa.Float(), nullable=True),
        sa.Column("cpu_system_s", sa.Float(), nullable=True),
        sa.Column("cpu_idle_s", sa.Float(), nullable=True),
        sa.Column("cpu_iowait_s", sa.Float(), nullable=True),
        sa.Column("cpu_irq_s", sa.Float(), nullable=True),
        sa.Column("cpu_softirq_s", sa.Float(), nullable=True),
        sa.Column("cpu_steal_s", sa.Float(), nullable=True),
        sa.Column("cpu_logical_count", sa.Integer(), nullable=True),
        sa.Column("cpu_run_queue", sa.Float(), nullable=True),
        sa.Column("cpu_blocked", sa.Float(), nullable=True),
        sa.Column("cpu_mce", sa.BigInteger(), nullable=True),
        sa.Column("mem_free_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_cached_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_buffered_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_available_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_limit_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_commit_usage_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_commit_limit_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_hardware_corrupted_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mem_oom_kill", sa.BigInteger(), nullable=True),
        sa.Column("paging_in", sa.BigInteger(), nullable=True),
        sa.Column("paging_out", sa.BigInteger(), nullable=True),
        sa.Column("paging_major", sa.BigInteger(), nullable=True),
        sa.Column("net_tcp_retransmits", sa.BigInteger(), nullable=True),
        sa.Column("net_conntrack_usage", sa.Integer(), nullable=True),
        sa.Column("net_conntrack_limit", sa.Integer(), nullable=True),
        sa.Column("boot_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
        sa.UniqueConstraint("server_id", "collected_at", name="uq_server_metrics_sid_ts"),
    )
    op.create_table(
        "server_net_io",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("iface_id", sa.String(length=64), nullable=False),
        sa.Column("iface_name", sa.String(length=256), nullable=True),
        sa.Column("rx_bytes", sa.BigInteger(), nullable=True),
        sa.Column("tx_bytes", sa.BigInteger(), nullable=True),
        sa.Column("rx_packets", sa.BigInteger(), nullable=True),
        sa.Column("tx_packets", sa.BigInteger(), nullable=True),
        sa.Column("rx_errors", sa.BigInteger(), nullable=True),
        sa.Column("tx_errors", sa.BigInteger(), nullable=True),
        sa.Column("rx_dropped", sa.BigInteger(), nullable=True),
        sa.Column("tx_dropped", sa.BigInteger(), nullable=True),
        sa.Column("link_speed_bps", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
        sa.UniqueConstraint("server_id", "iface_id", "collected_at", name="uq_server_net_io_sid_iface_ts"),
    )
    op.create_table(
        "server_pressure",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("resource", sa.String(length=16), nullable=False),
        sa.Column("scope", sa.String(length=8), nullable=False),
        sa.Column("stall_time_s", sa.Float(), nullable=True),
        sa.Column("ratio_avg10", sa.Float(), nullable=True),
        sa.Column("ratio_avg60", sa.Float(), nullable=True),
        sa.Column("ratio_avg300", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id", "collected_at"),
        sa.UniqueConstraint(
            "server_id", "resource", "scope", "collected_at", name="uq_server_pressure_sid_res_scope_ts"
        ),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("target_server_id", sa.Integer(), nullable=False),
        sa.Column("target_agent_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=32), nullable=True),
        sa.Column("exit_code", sa.SmallInteger(), nullable=True),
        sa.Column("signal_no", sa.SmallInteger(), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("stdout_tail", sa.Text(), nullable=True),
        sa.Column("stderr_tail", sa.Text(), nullable=True),
        sa.Column("task_policy", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_server_id"],
            ["server_inventory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(op.f("ix_tasks_target_agent_id"), "tasks", ["target_agent_id"], unique=False)
    op.create_index(
        "uq_tasks_pending_per_server_type",
        "tasks",
        ["target_server_id", "task_type"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###

    # 시계열 → TimescaleDB hypertable 변환 (autogenerate 미지원, 수동 보강).
    # if_not_exists => true — 멱등 (재시도·부분 실패 안전).
    for table in _HYPERTABLES:
        op.execute(f"SELECT create_hypertable('{table}', 'collected_at', if_not_exists => true)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_tasks_pending_per_server_type", table_name="tasks", postgresql_where=sa.text("status = 'pending'")
    )
    op.drop_index(op.f("ix_tasks_target_agent_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("server_pressure")
    op.drop_table("server_net_io")
    op.drop_table("server_metrics")
    op.drop_table("server_inventory_history")
    op.drop_table("server_filesystem")
    op.drop_table("server_disk_io")
    op.drop_table("server_disk_error")
    op.drop_table("server_cpu_core")
    op.drop_index("ix_server_inventory_service_categories", table_name="server_inventory", postgresql_using="gin")
    op.drop_table("server_inventory")
    op.drop_index(
        "uq_diagnostic_jobs_active_per_input",
        table_name="diagnostic_jobs",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_table("diagnostic_jobs")
    # ### end Alembic commands ###
